
CREATE OR REPLACE TABLE feat AS
SELECT STATION, DATE, TMAX, TMIN, PRCP, hour(DATE) AS hr, dayofweek(DATE) AS dow, month(DATE) AS mon, dayofyear(DATE) AS doy, LAG(TMAX, 1) OVER w AS y_lag1, LAG(TMAX, 2) OVER w AS y_lag2, LAG(TMAX, 3) OVER w AS y_lag3, LAG(TMAX, 365) OVER w AS y_lag365, LAG(TMAX, 730) OVER w AS y_lag730, LAG(TMAX, 1460) OVER w AS y_lag1460, AVG(TMAX) OVER (w ROWS BETWEEN 364 PRECEDING AND CURRENT ROW) AS y_ma_season, STDDEV(TMAX) OVER (w ROWS BETWEEN 364 PRECEDING AND CURRENT ROW) AS y_sd_season, TMAX - LAG(TMAX, 1) OVER w AS y_diff1, LAG(TMIN, 365) OVER w AS TMIN_lag_season, LAG(PRCP, 365) OVER w AS PRCP_lag_season, LEAD(TMAX, 1) OVER w AS y_h1, LEAD(TMAX, 2) OVER w AS y_h2, LEAD(TMAX, 3) OVER w AS y_h3
FROM clean WINDOW w AS (PARTITION BY STATION ORDER BY DATE);
